### ISSUE TITLE
print(moduleArt.archivePaper)

### ISSUE THREAD

**Issue by Cillancapital** [mewmewdevart/100DaysofCode#1]
https://github.com/mewmewdevart/100DaysofCode/blob/3e5339a9facd95313d354a898c307a8d77c78cbc/Day04/Project04/main.py#L93

**Comment by Cillancapital** [comment]
I think this should be written: 
print(moduleArt.archivePaper)

**Comment by mewmewdevart** [comment]
Hello, Cillancapital. How are you? Thank you for pointing out a errors in my code, I used your comment to return to the project and try to refactor it by applying some Python concepts. What did you think of my changes?

I used a list and a dictionary to store the game options and was able to access them individually, which reduced the number of if and elif statements in the code + with the plus of one function to draw the elements on screen.

**Comment by mewmewdevart** [comment]
I will close this issue, thanks for the feedback!
